name: NRK Core Components

headHtml: |
  <link rel="stylesheet" href="docs.css">
  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
  <!--<script>PropTypes = {}</script>
  <script src="https://cdn.jsdelivr.net/npm/preact/dist/preact.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/preact-compat/dist/preact-compat.min.js"></script>-->
  <script src="jsx/index.js"></script>
  <script src="core-components.min.js"></script>
  <script>
    // Create unstyle button
    document.documentElement.appendChild(document.createElement('unstyle')).onclick =
      function () { document.documentElement.classList.toggle('unstyle') }

    // Expose JSX and JS components to window
    Object.keys(CoreComponents).forEach(function (key) { window[key] = CoreComponents[key]})
    Object.keys(coreComponents).forEach(function (key) {
      window['core' + key[0].toUpperCase() + key.slice(1)] = coreComponents[key]
    })
  </script>

assets:
  - docs.css                # Include CSS for documentation
  - jsx/index.js            # Include JSX library
  - core-components.js      # Include JS src
  - core-components.min.js  # Include JS library

sidebar:
  background: "#3d2351"
  textColor: "#fff"

order:
  - Introduction
